service_name: payment-service
service_version: 1.0.0

database:
  host: "localhost"
  port: 3306
  name: "payment_db"
  user: "root"
  password: "root"
  max_open_connections: 20
  max_idle_connections: 10
  connection_max_lifetime: 60s

registration:
  etcd:
    endpoints:
      - localhost:2379
    dial_timeout: 5s